title: "Community Engaged CS"
subtitle: "CS 186-02 &bullet; Fall 2020"

piazza: "https://piazza.com/usfca/fall2020/cs186/home"
canvas: "https://usfca.instructure.com/courses/1594618"
github: "https://github.com/usf-cs186-fall2020"
zoom: "https://usfca.zoom.us/j/94143054441"

description: >-
  This course provides a structured opportunity for students to learn and participate in the departmental and local technical communities on and off campus. The course features activities including guest speakers from the local tech industry; faculty research talks; presentations by the campus career center and similar organizations; field trips to local meetup events; and opportunities for students to socialize and build relationships with one another.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
